---
    
- name: Terminate tagged instances
  hosts: tag_role_kube_masternode, tag_role_kube_workernode
  gather_facts: False
  tasks:
    - ec2_metadata_facts:
    - ec2:
        state: absent
        region: "{{ ansible_ec2_placement_region }}"
        instance_ids: "{{ ansible_ec2_instance_id }}"
      delegate_to: localhost