---
- hosts: tag_role_kube_masternode
  become: yes
  gather_facts: false
  environment:
    masternode_ip: "{{ play_hosts }}"
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: tag_role_kube_workernode
  vars:
    extra_vars:
      kube_masternode_ip: '{{ lookup("env", "kube_masternode_ip") }}'
  become: yes
  tasks:
    - name: join cluster
      shell: "{{ hostvars['{{ kube_masternode_ip }}'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
