---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Retrieve covered CVEs and MSids
    script: ../files/ds_protection_status.py {{ item }}
    loop: "{{ groups['demo'] }}"
    delegate_to: 127.0.0.1
    register: ds_protection_status

  - debug: 
      msg="{{ ds_protection_status }}"
