---
- name: Create EC2 instance
  hosts: localhost
  gather_facts: False
  tasks:
  - name: Get the variables
    include_vars: vars/secrets.yml

  - name: Create EC2 Instance
    ec2:
      aws_access_key: "{{ aws_access_key_id }}"
      aws_secret_key: "{{ aws_secret_access_key }}"
      key_name: ansible
      region: eu-central-1
      instance_type: t2.micro
      user_data: |
                 #!/bin/sh
                 echo "{{ id_rsa_pub }}" > /root/.ssh/authorized_keys
                 apt install -y python python-simplejson
      image: ami-5055cd3f
      wait: true
      count: 3
      group: orchestration
      vpc_subnet_id: subnet-0e34f3669e7450aa7
      assign_public_ip: no
    register: ec2

  - name: Add new instance to host group
    local_action: lineinfile
                  dest="/etc/ansible/hosts"
                  regexp={{ item.private_ip }}
                  insertafter="[demo]" line={{ item.private_ip }}
    with_items: "{{ ec2.instances }}"

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.private_ip }}"
      port: 22
      delay: 30
      timeout: 320
      state: started
    with_items: "{{ ec2.instances }}"
