---
- hosts: "{{ private_ip }}"
  tasks:
  - name: Update repositories cache if the last one is more than 3600 seconds ago
    apt:
      update_cache: yes
      cache_valid_time: 3600
  - name: Install the latest version of "apache2"
    apt:
      name: apache2
      state: present

- hosts: "{{ private_ip }}"
  roles:
    - role: ../roles/deep-security.deep-security-agent
      action: set-policy
      policy: Ubuntu 16 EC2 Web Server
    - role: ../roles/deep-security.deep-security-agent
      action: update-configuration
    - role: ../roles/deep-security.deep-security-agent
      action: run-recommendation-scans
