---
- name: Deep Security
#  gather_facts: no
  hosts: all
  vars:
    extra_vars:
      dsm_url: '{{ lookup("env", "dsm_url") }}'
      api_key: '{{ lookup("env", "api_key") }}'
  tasks:
  - name: tagging
    gce_tag:
      instance_name: "{{ inventory_hostname }}"
      project_id: erudite-variety-209408
      tags: dsa_no
      state: present
    environment:
      PYTHONPATH: "/usr/lib/python2.7/site-packages"

#  - uri:
#     url: "https://{{ dsm_url }}:4119/api/computers"
#      method: POST
#      validate_certs: no
#      body: ' { "hostName": "{{ inventory_hostname }}", "displayName": "{{ inventory_hostname }}", "description": "Created by Ansible", "groupID": 82 }'
#      headers:
#        Content-Type: "application/json"
#        api-secret-key: "{{ api_key }}"
#        api-version: "v1"
#    delegate_to: 127.0.0.1