---
- name: Deep Security query for registered project hosts
  gather_facts: no
  hosts: localhost
  vars:
    extra_vars:
      zone: '{{ lookup("env", "zone" }}'
      project_id: '{{lookup("env", "project_id" }}'
      dsm_url: '{{ lookup("env", "dsm_url") }}'
      api_key: '{{ lookup("env", "api_key") }}'
  tasks:
  - name: Test for computer already exists in DS
    uri:
      url: "https://{{ dsm_url }}:4119/api/computers/search"
      method: POST
      validate_certs: no
      body: ' { "maxItems": 5000, "searchCriteria": [ { "fieldName": "hostName", "stringTest": "equal", "stringValue": "%{{ project_id }}%", "stringWildcards": "true" } ] }'
      headers:
        Content-Type: "application/json"
        api-secret-key: "{{ api_key }}"
        api-version: "v1"
    register: search_result
    delegate_to: 127.0.0.1

  - name: Set computers list fact
    set_fact:
      computers: "{{ search_result.json.computers }}"

  - debug:
      msg: Computers "{{ computers }}"

  - debug:
      msg: Computers 2 "{{ item }}"
    with_items: computers['hostName']

- name: Query GCE inventory for DS registered project hosts
  gather_facts: no
  hosts: all
  vars:
    extra_vars:
      zone: '{{ lookup("env", "zone" }}'
      project_id: '{{lookup("env", "project_id" }}'
      dsm_url: '{{ lookup("env", "dsm_url") }}'
      api_key: '{{ lookup("env", "api_key") }}'
  tasks:
  - debug:
      msg: "{{ hostvars['localhost'].computers }}"

  - name: Test if computer exists in gce project
    debug:
      msg: "{{ item }}"
    with_inventory_hostnames:
      - all: instance

#     when: search_result.json.computers == []