- name: Delete computers from Deep Security
  gather_facts: no
  hosts: localhost
  vars:
    extra_vars:
      dsm_url: '{{ lookup("env", "dsm_url") }}'
      api_key: '{{ lookup("env", "api_key") }}'
  tasks:
  - name: Get ID of to be deleted computers in Deep Security
    uri:
      url: "https://{{ dsm_url }}:4119/api/computers/search"
      method: POST
      validate_certs: no
      #body: ' { "maxItems": 5000, "searchCriteria": [ { "fieldName": "hostName", "stringTest": "equal", "stringValue": "%{{ project_id }}%", "stringWildcards": "true" } ] }'
      body: ' { "maxItems": 1, "searchCriteria": [ { "fieldName": "hostName", "stringTest": "equal", "stringValue": "{{ computer }}" } ] }'
      headers:
        Content-Type: "application/json"
        api-secret-key: "{{ api_key }}"
        api-version: "v1"
    register: search_result
    delegate_to: 127.0.0.1

  - name: Set computers list fact
    set_fact:
      dsc: "{{ search_result.json }}"

  - name: Iterate JSON
    set_fact:
      ds_computer_item: "{{ item.ID }}"
    with_items: "{{ dsc.computers }}"
    register: dsc_list

  - name: Create Fact List
    set_fact:
      dscs: "{{ dsc_list.results | map(attribute='ansible_facts.ds_computer_item') | list }}"

  - name: Print Fact
    debug: var=dscs

#    - name: Delete computer in Deep Security
#      uri:
#        url: "https://{{ dsm_url }}:4119/api/computers/"
#        method: DELETE
#        validate_certs: no
##        body: ' { "maxItems": 5000, "searchCriteria": [ { "fieldName": "hostName", "stringTest": "equal", "stringValue": "%{{ project_i$
#        headers:
#          Content-Type: "application/json"
#          api-secret-key: "{{ api_key }}"
#          api-version: "v1"
 #   with_items: "{{ hostvars['localhost'].dscs | difference(hostvars['localhost'].gcecs) }}"