---
- name: Deep Security
  gather_facts: no
  hosts: all
  vars:
    extra_vars:
      zone: '{{ lookup("env", "zone" }}'
      project_id: '{{lookup("env", "project_id" }}'
  tasks:
#  - name: labling
#    gce_labels:
#      labels:
#        environment: test
#        dsa: no
#      resource_url: https://console.cloud.google.com/compute/instancesDetail/zones/europe-west2-c/instances/instance-1
#      state: present
#    delegate_to: 127.0.0.1

  - name: Stat dsa_control (test for dsa)
    stat:
      path: /opt/ds_agent/dsa_control
    register: stat_result

  - block:
    - name: tagging if no dsa
      gce_tag:
        instance_name: "{{ inventory_hostname }}"
        zone: "{{ zone }}"
        project_id: "{{ project_id }}"
        tags: dsano
        state: present
      delegate_to: 127.0.0.1

    - name: tagging if no dsa
      gce_tag:
        instance_name: "{{ inventory_hostname }}"
        zone: "{{ zone }}"
        project_id: "{{ project_id }}"
        tags: dsayes
        state: absent
      delegate_to: 127.0.0.1
    when: stat_result.stat.exists == False
  
  - block:
    - name: tagging is dsa installed
      gce_tag:
        instance_name: "{{ inventory_hostname }}"
        zone: "{{ zone }}"
        project_id: "{{ project_id }}"
        tags: dsayes
        state: present
      delegate_to: 127.0.0.1

    - name: tagging is dsa installed
      gce_tag:
        instance_name: "{{ inventory_hostname }}"
        zone: "{{ zone }}"
        project_id: "{{ project_id }}"
        tags: dsano
        state: absent
      delegate_to: 127.0.0.1
    when: stat_result.stat.exists == True
