---
- hosts: tag_role_kube_masternode
  gather_facts: false
  tasks:
    - name: Copy token script to master
      copy:
        src: ../files/bearertoken.sh
        dest: /home/ubuntu
        owner: ubuntu
        group: ubuntu
        mode: 0755

- hosts: tag_role_kube_masternode
  become: yes
  become_user: ubuntu
  gather_facts: false
  tasks:
    - name: Create a bz2 archive of .kube
      archive:
        path: /home/ubuntu/.kube
        dest: /home/ubuntu/dot_kube.tar.bz2
        format: bz2

    - name: Get bearer token
      shell: /home/ubuntu/bearertoken.sh

- hosts: tag_role_kube_masternode
  gather_facts: false
  tasks:
    - name: Fetch .kube config package
      fetch: 
        src: /home/ubuntu/dot_kube.tar.bz2
        dest: /tmp

    - name: Fetch bearer token
      fetch:
        src: /home/ubuntu/admintoken.txt
        dest: /tmp
