---
- hosts: tag_role_kube_masternode
  vars:
    extra_vars:
      activation_code: '{{ lookup("env", "activation_code") }}'
  become: yes
  become_user: ubuntu
  gather_facts: false
  tasks:
    - name: Pull smartcheck helm
      git:
        repo: 'https://github.com/deep-security/smartcheck-helm'
        dest: /home/ubuntu/smartcheck-helm

    - name: Create overrides file
      copy:
        dest: "/home/ubuntu/smartcheck-helm/overrides.yaml"
        content: |
          service:
            type: ClusterIP
          persistence:
            enabled: false

    - name: Install DSSC
      shell: helm install --namespace smartcheck --set auth.masterPassword=trendmicro --set activationCode={{ activation_code }} --name deepsecurity-smartcheck --values /home/ubuntu/smartcheck-helm/overrides.yaml /home/ubuntu/smartcheck-helm

- hosts: tag_role_kube_workernode
  become: yes
  tasks:
    - name: Set promic on workernodes
      shell: ip link set cni0 promisc on

- hosts: tag_role_kube_masternode
  become: yes
  tasks:
  - debug:
      msg:
        - "# Access Smartcheck:"
        - "export POD_NAME=$(kubectl get pods --namespace smartcheck -l 'service=proxy,release=deepsecurity-smartcheck' -o jsonpath='{.items[0].metadata.name}')"
        - "kubectl port-forward --namespace smartcheck $POD_NAME 8443:8443"
        - "echo Application URL: https://127.0.0.1:8443"
        - "echo Username: $(kubectl get --namespace smartcheck secrets -o jsonpath='{.data.userName }' deepsecurity-smartcheck-auth | base64 --decode)"
        - "echo Password: $(kubectl get --namespace smartcheck secrets -o jsonpath='{.data.password }' deepsecurity-smartcheck-auth | base64 --decode)"

  - debug:
      msg:
        - "# Change Activation Code:"
        - "helm upgrade --set activationCode=<CODE> --values overrides.yaml --set auth.masterPassword=<PASSWORD> deepsecurity-smartcheck ."
        - "kubectl delete pods --namespace smartcheck -l 'service=scan,release=deepsecurity-smartcheck'"
