---
- name: Install Wordpress
  hosts: tag_role_web_server
  tasks:
  - name: Update repositories cache if the last one is more than 3600 seconds ago
    apt:
      update_cache: yes
      cache_valid_time: 3600
  - name: Install the latest version of "wordpress"
    apt:
      name:
        - php7.0
        - php7.0-mysql
        - libapache2-mod-php7.0
        - php7.0-cli
        - php7.0-gd 
        - wordpress
      state: present

- name: Install MySQL database server
  hosts: tag_role_database_server
  tasks:
  - name: Update repositories cache if the last one is more than 3600 seconds ago
    apt:
      update_cache: yes
      cache_valid_time: 3600
  - name: Install the latest version of "mysql-server"
    apt:
      name:
        - mysql-server
        - python-mysqldb
      state: present
      