---
- hosts: localhost
  gather_facts: no
  vars:
    extra_vars:
      dsm_url: '{{ lookup("env", "dsm_url") }}'
      api_key: '{{ lookup("env", "api_key") }}'
      hostname: '{{ lookup("env", "hostname") }}'
  tasks:
  - name: Query Deep Security Protection Status
    ds_protection_status:
      hostname: "{{ hostname }}"
      dsm_url: "https://{{ dsm_url }}:4119"
      api_key: "{{ api_key }}"
    register: ds_result

  - name: Print result
    debug:
      msg: "{{ ds_result.json }}"
