---
- hosts: tag_env_tower
  roles:
    - role: ../roles/deep-security.deep-security-agent
      operation: set-policy-by-name
      policy_name: Ubuntu 16 EC2
    - role: ../roles/deep-security.deep-security-agent
      operation: update-configuration
    - role: ../roles/deep-security.deep-security-agent
      operation: run-recommendation-scans
