---
- name: Create EC2 instance
  hosts: localhost
  gather_facts: False
  vars:
    aws:
      access_key: '{{ lookup("env", "AWS_ACCESS_KEY_ID") }}'
      secret_key: '{{ lookup("env", "AWS_SECRET_ACCESS_KEY") }}'
    extra_vars:
      id_rsa_pub: '{{ lookup("env", "id_rsa_pub") }}'

  tasks:
  - name: Create EC2 Instance
    ec2:
      aws_access_key: "{{ aws.access_key }}"
      aws_secret_key: "{{ aws.secret_key }}"
      key_name: ansible
      region: eu-central-1
      instance_type: t2.micro
      user_data: |
                 #!/bin/sh
                 echo "{{ id_rsa_pub }}" > /root/.ssh/authorized_keys
                 apt install -y python python-simplejson
      image: ami-5055cd3f
      wait: true
      count: 3
      group: orchestration
      vpc_subnet_id: subnet-0e34f3669e7450aa7
      assign_public_ip: no
      instance_tags:
        env: demo
        role: web-server
    register: ec2

  - name: Add new instance to host group
    local_action: lineinfile
                  dest="/etc/ansible/hosts"
                  regexp={{ item.private_ip }}
                  insertafter="[demo]" line={{ item.private_ip }}
    with_items: "{{ ec2.instances }}"

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.private_ip }}"
      port: 22
      delay: 30
      timeout: 320
      state: started
    with_items: "{{ ec2.instances }}"
