---
- name: Prepare MySQL database for Wordpress
  hosts: tag_role_database_server
  vars:
    extra_vars:
      mysql_db: '{{ lookup("env", "mysql_db") }}'
      mysql_user: '{{ lookup("env", "mysql_user") }}'
      mysql_password: '{{ lookup("env", "mysql_password") }}'

  tasks:
  - name: Create wordpress database
    mysql_db:
      name: "{{ mysql_db }}"
      state: present
  - name: Create mysql user
    mysql_user:
      name: "{{ mysql_user }}"
      state: "{{ mysql_password }}"
      priv: '*.*:ALL'
      state: present

- name: Configure Apache2 for Wordpress
  hosts: tag_role_web_server
  vars:
    extra_vars:
      mysql_db: '{{ lookup("env", "mysql_db") }}'
      mysql_user: '{{ lookup("env", "mysql_user") }}'
      mysql_password: '{{ lookup("env", "mysql_password") }}'
      mysql_address: '{{ lookup("env", "mysql_address") }}'
  tasks:
#  - name: Create wordpress directory
#    file:
#      path: "/var/www/wordpress"
#      state: "directory"
#  - name: Update default Apache site
#    lineinfile:
#      dest: "/etc/apache2/sites-enabled/000-default.conf"
#      regexp: "(.)+DocumentRoot /var/www/html"
#      line: "DocumentRoot /var/www/wordpress"
#  - name: Restart apache2
#    service:
#      name: apache2
#      state: restarted

  - name: Copy sample config file
    copy:
      remote_src: true
      src: "/usr/share/wordpress/wp-config-sample.php"
      dest: "/etc/wordpress/config-{{ inventory_hostname }}.php"
  - name: Update WordPress config file
    lineinfile:
      dest=/var/www/wordpress/wp-config.php
      regexp="{{ item.regexp }}"
      line="{{ item.line }}"
    with_items:
      - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{ mysql_db }}');"}
      - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{ mysql_user }}');"}
      - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{ mysql_password }}');"}
      - {'regexp': "define\\('DB_HOST', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{ mysql_address }}');"}
  - name: Configure apache site
    copy:
      dest: "/etc/apache2/sites-available/wordpress.conf"
      content: |
        Alias /blog /usr/share/wordpress
        <Directory /usr/share/wordpress>
            Options FollowSymLinks
            AllowOverride Limit Options FileInfo
            DirectoryIndex index.php
            Order allow,deny
            Allow from all
        </Directory>
        <Directory /usr/share/wordpress/wp-content>
            Options FollowSymLinks
            Order allow,deny
            Allow from all
        </Directory>
  - name: Enable Wordpress site
    command: a2ensite wordpress.conf
  - name: Restart apache2
    service:
      name: apache2
      state: restarted