---
- name: Deep Security with iptables
  hosts: all
  vars:
    extra_vars:
      dsm_url: '{{ lookup("env", "dsm_url") }}'
  tasks:
  - uri:
      url: "https://{{ dsm_url }}:4119/api/computers"
      method: POST
	  body: "{ "hostName": {{ inventory_hostname }}, "displayName": {{ inventory_hostname }}, "description": "Created by Ansible", "groupID": 82 }"
	  headers:
        Content-Type: "application/json"
        api-secret-key: '4:+y5SkE7jAEG3Jt7hoeKsh34mBONgudoDrYyijLv2XXM='
        api-version: "v1"
